#!/bin/bash

echo "🔧 Twitter Cloudflare Fix Script"
echo "================================"

echo "Current status:"
echo "- IP: $(curl -s ifconfig.me)"
echo "- Twitter API: $(curl -s -o /dev/null -w "%{http_code}" "https://api.twitter.com/2/users/by/username/elonmusk" -H "Authorization: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA") (403 = blocked)"

echo ""
echo "🚀 SOLUTION OPTIONS:"
echo "===================="

echo "1. 🏠 USE VPN (RECOMMENDED):"
echo "   - ExpressVPN, NordVPN, or ProtonVPN"
echo "   - Connect to US/EU server"
echo "   - Then run: twscrape login_accounts"

echo ""
echo "2. 🏢 USE PROXY SERVICE:"
echo "   - Get residential proxies from:"
echo "     * Bright Data (luminati.io) - $500/month"
echo "     * Smart Proxy (smartproxy.com) - $75/month"
echo "     * Oxylabs (oxylabs.io) - $75/month"
echo "   - Add to twscrape: twscrape --proxy 'http://user:pass@proxy:8080' login_accounts"

echo ""
echo "3. 🆕 CREATE FRESH ACCOUNTS:"
echo "   - Run: python3 create_accounts.py"
echo "   - Follow instructions to create new Twitter accounts"
echo "   - Use VPN during account creation"

echo ""
echo "4. 🖥️  USE VPS/DIFFERENT IP:"
echo "   - AWS Lightsail, DigitalOcean droplet ($5/month)"
echo "   - Choose US region"
echo "   - Install scraper there"

echo ""
echo "🧪 TEST YOUR FIX:"
echo "================="
echo "After applying any solution above, test with:"
echo ""
echo "twscrape accounts"
echo "twscrape login_accounts"
echo "python3 test_scraper.py"
echo ""
echo "✅ If login succeeds, run: python3 scraper.py"

echo ""
echo "📞 NEED HELP?"
echo "============="
echo "- Check current IP: curl ifconfig.me"
echo "- Test API access: curl -s -o /dev/null -w \"%{http_code}\" \"https://api.twitter.com/2/users/by/username/elonmusk\""
echo "- Should return 200 (not 403) when working"
