#!/bin/bash

echo "🚀 System-Wide VPN Setup for Twitter Scraping"
echo "=============================================="

echo "Current status:"
echo "- IP: $(curl -s ifconfig.me)"
echo "- Location: $(curl -s ipinfo.io/country)"
echo "- Twitter API: $(curl -s -o /dev/null -w "%{http_code}" "https://api.twitter.com/2/users/by/username/elonmusk" -H "Authorization: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA") (403 = blocked)"

echo ""
echo "📱 RECOMMENDED VPN APPS (System-wide):"
echo "======================================"

echo "1. 🆓 PROTONVPN (Free, unlimited):"
echo "   - Download: https://protonvpn.com/download"
echo "   - Install and connect to US server"
echo "   - Free tier works for scraping"

echo ""
echo "2. 🆓 WINDSCRIBE (Free, 10GB/month):"
echo "   - Download: https://windscribe.com/download"
echo "   - Install and connect to US server"

echo ""
echo "3. 💰 EXPRESSVPN (Paid, $8/month):"
echo "   - Download: https://expressvpn.com"
echo "   - Fast and reliable for scraping"

echo ""
echo "4. 💰 NORDVPN (Paid, $3/month):"
echo "   - Download: https://nordvpn.com"
echo "   - Good for developers"

echo ""
echo "🔧 VERIFICATION STEPS:"
echo "======================"

echo "After installing and connecting VPN:"
echo ""
echo "1. Check IP change:"
echo "   ./setup_vpn.sh"
echo "   # Should show US IP and 'US' location"
echo ""
echo "2. Test Twitter access:"
echo "   curl -s -o /dev/null -w \"%{http_code}\" \"https://api.twitter.com/2/users/by/username/elonmusk\""
echo "   # Should return 200 (not 403)"
echo ""
echo "3. Login Twitter accounts:"
echo "   twscrape login_accounts"
echo ""
echo "4. Start scraping:"
echo "   python3 scraper.py"

echo ""
echo "⚠️  IMPORTANT NOTES:"
echo "==================="
echo "- VPN must be connected BEFORE running twscrape"
echo "- Keep VPN connected during scraping"
echo "- If login still fails, try different US server"
echo "- Some free VPNs get blocked too - try paid ones"

echo ""
echo "🆘 ALTERNATIVE: Use VPS"
echo "======================="
echo "If VPN doesn't work:"
echo "1. Get DigitalOcean droplet (\$6/month)"
echo "2. Choose US region"
echo "3. SSH into it and run scraper there"
echo "4. No IP blocking issues"
